services:
  web:
    build: .
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    restart: always
    environment:
      - REDIS_HOST=redis
      - BYBIT_EXCHANGE_URL=${BYBIT_EXCHANGE_URL}
      - BYBIT_TESTNET_EXCHANGE=${BYBIT_TESTNET_EXCHANGE}
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - BOT_API_KEY=${BOT_API_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/bybit_trade_entry_bot
  redis:
    image: "redis:alpine"
